### ISSUE TITLE
Tamanho Logo Mobile

### ISSUE THREAD

**Issue by gustavo-marcialis** [bolodissenoura/lantera-luminosa#1]
O tamanho da logo no header no mobile tá muito grande, o que fez quebrar pra linha de baixo o ícone pra acessar a lista de páginas.![Screenshot_20240327_125913_Chrome.png](https://github.com/bolodissenoura/lantera-luminosa/assets/76740936/a7752949-c368-4094-b09c-5706042b0fcd)

**Comment by Luiginicoletti** [comment]
WIP
