### ISSUE TITLE
Trocar fotos

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#11]
foto da compreesao profunda e 
foto da voz com poder

 trocar por essas do drive:

**Comment by FIXER3600** [comment]
Trocar por quais fotos? Faltou o link do drive

**Comment by bolodissenoura** [comment]
Questinei a cliente, ela vai passar em breve as fotos.

**Comment by bolodissenoura** [comment]
https://github.com/bolodissenoura/lantera-luminosa/issues/35
