### ISSUE TITLE
Tamanho Vídeos Mobile

### ISSUE THREAD

**Issue by gustavo-marcialis** [bolodissenoura/lantera-luminosa#2]
Ajustar o tamanho dos vídeos em dispositivos pequenos (smartphone).![Screenshot_20240327_132534_Chrome.png](https://github.com/bolodissenoura/lantera-luminosa/assets/76740936/e1e1a8e4-bf9b-4a2c-97cb-6fb718954596)

**Comment by Evandrosc** [comment]
- #18
