### ISSUE TITLE
Adicionar informacao 

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#39]
A cliente quer que tenha um CTA para levar a palestra do instituto.

Algo como: Leve a palestra do Lanterna Luminosa para sua cidade ou empresa, contato:  institutolanternaluminosa@gmail.com

Use sua imaginacao, pode fazer uma section pequena de CTA ( Call To Action ).

**Comment by Gabset07** [comment]
Fiz uma alteração no simples no CTA.Vê se ficou do seu agrado.
