### ISSUE TITLE
Layout Mobile Quebrado

### ISSUE THREAD

**Issue by gustavo-marcialis** [bolodissenoura/lantera-luminosa#50]
O layout no smartphone tá quebrado.![Screenshot_20240330_002921_Chrome.png](https://github.com/bolodissenoura/lantera-luminosa/assets/76740936/c8c38758-32c0-463f-9468-55252ca9e4d0)

**Comment by davimgfx** [comment]
Bom dia, essa issue já foi resolvida.

![Screenshot_2024-03-30-10-36-11-061_com android chrome](https://github.com/bolodissenoura/lantera-luminosa/assets/118557337/f0585a22-44bd-4690-a03f-6d6316c2299e)

**Comment by gustavo-marcialis** [comment]
Aqui ainda aparece quebrado o layout...
![Screenshot_20240330_234205_Chrome.png](https://github.com/bolodissenoura/lantera-luminosa/assets/76740936/868d57e6-4d31-42bb-9981-16d094444c63)
