### ISSUE TITLE
Remover esses accordions

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#53]
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/73969685/9622e2e8-8594-4920-af59-bece6284750f)
Remover essa parte

**Comment by MayconPadilha** [comment]
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/58276390/56855bda-2c1d-4a58-9276-a1154c7592d3)
Remoção das faqs mencionadas
