### ISSUE TITLE
Adiconar texto comovente

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#54]
Colocar um texto legal aqui nessa parte
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/73969685/dd94fbaa-9cae-4c2a-8fc6-8df254c8e71c)

**Comment by trp02** [comment]
Hello, what kind of legal text were you thinking?

**Comment by JuliocesarWpedro** [comment]
Coloquei lá
