### ISSUE TITLE
No item procure ajuda -> cadastrar novos numeros de whatsapp

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#6]
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/73969685/da968398-a53f-48d8-a6c2-2fd2316a773e)

**Comment by bolodissenoura** [comment]
numero de zap: 
+55 41 9164-1633 ( Emanoelli ) 
+55 41 9164-1633 ( Emanoelli )

**Comment by HenriqueOliveiraa** [comment]
queria entender melhor em qual dessas seções seria melhor para encaixar o contato

trago também um preview do caso de colocar em uma das sections do fim do código, relacionado ao contato também

![image](https://github.com/bolodissenoura/lantera-luminosa/assets/109089389/3e544391-a625-4f6c-aff0-2a53c6f22406)

![image](https://github.com/bolodissenoura/lantera-luminosa/assets/109089389/4b7fc105-2ee3-4056-bada-44c1b1a8910c)

**Comment by bolodissenoura** [comment]
Perfeito.
