### ISSUE TITLE
Icone de fechar modal nao fecha

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#7]
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/73969685/a9a1c755-5d8c-49e4-a65a-c54d92e2c3d1)

**Comment by JuliocesarWpedro** [comment]
Eu testei aqui, e está funcionando normalmente

**Comment by brunopdt** [comment]
Pelo que testei, ao abrir o modal pelo item da navbar "buscar ajuda", o X funciona normalmente. Mas se abrir pelo ícone de chat flutuante embaixo, clicar no X não está fechando @JuliocesarWpedro.
