### ISSUE TITLE
Mudanças gerais

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#71]
Vou adicionar uma unica issu, mas sao varios casos, entao conforme for resolvendo favor colocar o nomero e o link da PR.
O que tem ✅ é pq está feito.

✅ 1-	Mudar a logo para a cor branca
2-	Colocar o mini cv com a foto dos diretores dentro do ícone :sobre o instituto, ( está no drive )assim como o vídeo institucional  que também está no drive.
✅3-	No item sobre nós, no segundo parágrafo: Atuamos de maneira integral, fornecendo suporte essencial em todos os aspectos da vida das mulheres afetadas, incluindo as áreas (colocar dois pontos aqui) :profissional,
4-	Nos ícones voz com poder, trocar os corações pela imagem da lanterna luminosa (foto está no drive)
✅5-	Na parte compreensão profunda, no primeiro ícone, a triste realidade, tem um texto com os dados da violência pra incluir (está no drive)
6-	Inserir vídeo institucional do ill (está no drive) 
7-	No item, ainda restam dúvidas, está só o whats da emanoelli e falta o meu 41- 99830 9091 e ela é vice-presidente, eu sou a presidente, mas acho que devemos por somente os números sem os nossos nomes e também por o email 
8-	Falta o ícone contendo os eventos de 2021 a 2023, que enviei em power point no drive e eu vou por os dois eventos de 2024
✅ 9-	Colocar na parte de perguntas frequentes, abaixo de conheça nossa história, conte sua história, onde a pessoa pode contar sua história de abuso ou de seu relacionamento.
10 - Na cabeceira, do lado direito, ao lado do ícone busque ajuda, colocar o item contato tbem, para os contatos no início e no fim do site.

**Comment by bolodissenoura** [comment]
O drive que ela se refere é esse https://drive.google.com/drive/folders/1-62s2ucQ6UJwOS-lxT4l1ABDiN_5QuIv

**Comment by gabrielrsep** [comment]
Item 4
https://github.com/bolodissenoura/lantera-luminosa/pull/74
