### ISSUE TITLE
Correcoes ortograficas/ palavras

### ISSUE THREAD

**Issue by bolodissenoura** [bolodissenoura/lantera-luminosa#8]
"diversos tipos de abuso" -> todos tipos de abuso
"incluindo areas" -> incluindo as areas: profissional, financeira ... [ aqui deixar essas areas no singular, pois algumas estao no plural ]
Colocar entre aspas: 
![image](https://github.com/bolodissenoura/lantera-luminosa/assets/73969685/3fe36450-8381-4880-b256-0883503515b9)

**Comment by FIXER3600** [comment]
#26
